"""
SQL Exporter
"""
from typing import Union, List
from models.schemas import Movie, TVShow
from .base import BaseExporter


class SQLExporter(BaseExporter):
    """Export data to SQL INSERT statements"""
    
    def _escape_sql(self, value) -> str:
        """Escape SQL string value"""
        if value is None:
            return "NULL"
        if isinstance(value, bool):
            return "1" if value else "0"
        if isinstance(value, (int, float)):
            return str(value)
        # Escape single quotes
        return "'" + str(value).replace("'", "''") + "'"
    
    def _format_movie(self, movie: dict) -> str:
        lines = [
            "-- Movie Data",
            "-- Generated by MovieFetchBot",
            "",
            "CREATE TABLE IF NOT EXISTS movies (",
            "    id INTEGER PRIMARY KEY,",
            "    title TEXT NOT NULL,",
            "    original_title TEXT,",
            "    overview TEXT,",
            "    release_date TEXT,",
            "    runtime INTEGER,",
            "    vote_average REAL,",
            "    vote_count INTEGER,",
            "    popularity REAL,",
            "    poster_path TEXT,",
            "    tagline TEXT,",
            "    budget INTEGER,",
            "    revenue INTEGER,",
            "    status TEXT,",
            "    genres TEXT",
            ");",
            "",
        ]
        
        genres = ', '.join(g.get('name', '') for g in movie.get('genres', []))
        
        lines.append(f"INSERT INTO movies (id, title, original_title, overview, release_date, runtime, vote_average, vote_count, popularity, poster_path, tagline, budget, revenue, status, genres) VALUES (")
        lines.append(f"    {movie.get('id', 0)},")
        lines.append(f"    {self._escape_sql(movie.get('title'))},")
        lines.append(f"    {self._escape_sql(movie.get('original_title'))},")
        lines.append(f"    {self._escape_sql(movie.get('overview'))},")
        lines.append(f"    {self._escape_sql(movie.get('release_date'))},")
        lines.append(f"    {movie.get('runtime') or 'NULL'},")
        lines.append(f"    {movie.get('vote_average') or 'NULL'},")
        lines.append(f"    {movie.get('vote_count') or 'NULL'},")
        lines.append(f"    {movie.get('popularity') or 'NULL'},")
        lines.append(f"    {self._escape_sql(movie.get('poster_path'))},")
        lines.append(f"    {self._escape_sql(movie.get('tagline'))},")
        lines.append(f"    {movie.get('budget') or 'NULL'},")
        lines.append(f"    {movie.get('revenue') or 'NULL'},")
        lines.append(f"    {self._escape_sql(movie.get('status'))},")
        lines.append(f"    {self._escape_sql(genres)}")
        lines.append(");")
        
        if movie.get('cast'):
            lines.extend([
                "",
                "CREATE TABLE IF NOT EXISTS movie_cast (",
                "    movie_id INTEGER,",
                "    name TEXT,",
                "    character TEXT,",
                "    FOREIGN KEY (movie_id) REFERENCES movies(id)",
                ");",
                ""
            ])
            for c in movie['cast']:
                lines.append(f"INSERT INTO movie_cast (movie_id, name, character) VALUES ({movie.get('id', 0)}, {self._escape_sql(c.get('name'))}, {self._escape_sql(c.get('character'))});")
        
        return '\n'.join(lines)
    
    def _format_tv(self, tv: dict) -> str:
        lines = [
            "-- TV Show Data",
            "-- Generated by MovieFetchBot",
            "",
            "CREATE TABLE IF NOT EXISTS tv_shows (",
            "    id INTEGER PRIMARY KEY,",
            "    name TEXT NOT NULL,",
            "    original_name TEXT,",
            "    overview TEXT,",
            "    first_air_date TEXT,",
            "    last_air_date TEXT,",
            "    number_of_seasons INTEGER,",
            "    number_of_episodes INTEGER,",
            "    vote_average REAL,",
            "    vote_count INTEGER,",
            "    popularity REAL,",
            "    poster_path TEXT,",
            "    tagline TEXT,",
            "    status TEXT,",
            "    genres TEXT",
            ");",
            "",
        ]
        
        genres = ', '.join(g.get('name', '') for g in tv.get('genres', []))
        
        lines.append(f"INSERT INTO tv_shows (id, name, original_name, overview, first_air_date, last_air_date, number_of_seasons, number_of_episodes, vote_average, vote_count, popularity, poster_path, tagline, status, genres) VALUES (")
        lines.append(f"    {tv.get('id', 0)},")
        lines.append(f"    {self._escape_sql(tv.get('name'))},")
        lines.append(f"    {self._escape_sql(tv.get('original_name'))},")
        lines.append(f"    {self._escape_sql(tv.get('overview'))},")
        lines.append(f"    {self._escape_sql(tv.get('first_air_date'))},")
        lines.append(f"    {self._escape_sql(tv.get('last_air_date'))},")
        lines.append(f"    {tv.get('number_of_seasons') or 'NULL'},")
        lines.append(f"    {tv.get('number_of_episodes') or 'NULL'},")
        lines.append(f"    {tv.get('vote_average') or 'NULL'},")
        lines.append(f"    {tv.get('vote_count') or 'NULL'},")
        lines.append(f"    {tv.get('popularity') or 'NULL'},")
        lines.append(f"    {self._escape_sql(tv.get('poster_path'))},")
        lines.append(f"    {self._escape_sql(tv.get('tagline'))},")
        lines.append(f"    {self._escape_sql(tv.get('status'))},")
        lines.append(f"    {self._escape_sql(genres)}")
        lines.append(");")
        
        if tv.get('episodes'):
            lines.extend([
                "",
                "CREATE TABLE IF NOT EXISTS tv_episodes (",
                "    id INTEGER PRIMARY KEY,",
                "    tv_id INTEGER,",
                "    season_number INTEGER,",
                "    episode_number INTEGER,",
                "    name TEXT,",
                "    overview TEXT,",
                "    air_date TEXT,",
                "    runtime INTEGER,",
                "    vote_average REAL,",
                "    FOREIGN KEY (tv_id) REFERENCES tv_shows(id)",
                ");",
                ""
            ])
            for ep in tv['episodes']:
                lines.append(f"INSERT INTO tv_episodes (id, tv_id, season_number, episode_number, name, overview, air_date, runtime, vote_average) VALUES ({ep.get('id', 0)}, {tv.get('id', 0)}, {ep.get('season_number', 0)}, {ep.get('episode_number', 0)}, {self._escape_sql(ep.get('name'))}, {self._escape_sql(ep.get('overview'))}, {self._escape_sql(ep.get('air_date'))}, {ep.get('runtime') or 'NULL'}, {ep.get('vote_average') or 'NULL'});")
        
        return '\n'.join(lines)
    
    def export(self, data: Union[Movie, TVShow, List[Union[Movie, TVShow]]]) -> str:
        if isinstance(data, list):
            parts = []
            for item in data:
                prepared = self.prepare_data(item)
                if 'title' in prepared:
                    parts.append(self._format_movie(prepared))
                else:
                    parts.append(self._format_tv(prepared))
            return '\n\n'.join(parts)
        else:
            prepared = self.prepare_data(data)
            if hasattr(data, 'title'):
                return self._format_movie(prepared)
            return self._format_tv(prepared)
    
    def get_file_extension(self) -> str:
        return "sql"
    
    def get_content_type(self) -> str:
        return "application/sql"
